lang: en
title: Natty Dev
copyright: © 2024. All rights reserved.

theme: jekyll-theme-primer
permalink: /blog/:year/:month/:day/:title/
menu:
  - title: Blog
    url:   /blog/
  - title: Showcase
    url:   /showcase/
  - title: Resume
    url:   /resume/
  - title: About
    url:   /about/

collections:
  showcase:
    output: true
    permalink: /showcase/:title/
