lang: sv
title: Natty Dev
copyright: © 2024. All rights reserved.

theme: jekyll-theme-primer

menu:
  - title: Blog
    url:   /_posts/
  - title: Showcase
    url:   /showcase/
  - title: Resume
    url:   /resume/
  - title: About
    url:   /about/

  collections:
    showcase:
      output: true
      permalink: /showcase/:title/