lang: en
title: Peter Johannessen
copyright: © 2025. All rights reserved.
tagline: "From classic BI to future-ready data engineering"
description: "Exploring dbt, Power BI, DAX tricks, SQL villains & data magic and more"

logo: "/assets/img/logo.png"

theme: jekyll-theme-primer
permalink: /blog/:year/:month/:day/:title/
url: "https://pejo422.github.io/"
baseurl: "/mySite"



menu:
  - title: Blog
    url:   /blog/
  - title: Showcase
    url:   /showcase/
  - title: Resume
    url:   /resume/
  - title: About
    url:   /about/

collections:
  showcase:
    output: true
    permalink: /showcase/:title/

author:
  name:  Peter Johannessen
  email: pejo422@outlook.com
  picture: /assets/img/profile.jpg
  social:
    github: pejo422
    linkedin: peter-johannessen
