lang: sv
title: Natty Dev
copyright: © 2024. All rights reserved.

theme: jekyll-theme-primer

menu:
  - title: Blog
    url:   /blog/
  - title: Showcase
    url:   /showcase/
  - title: Resume
    url:   /resume/
  - title: About
    url:   /about/